# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""Dictionary containing commutation relations of unparameterizable standard gates. The dictionary key
is defined by a pair of gates and, optionally, their relative placement to each other, i.e.:

   ┌───┐┌───┐
q: ┤ X ├┤ Z ├    -> standard_gates_commutations[StandardGate.XGate, StandardGate.ZGate] = False
   └───┘└───┘

or
          ┌───┐
q_0: ──■──┤ X ├
     ┌─┴─┐└─┬─┘  -> standard_gates_commutations[StandardGate.CXGate, StandardGate.CYGate][1, 0] = False
q_1: ┤ Y ├──■──
     └───┘

or

q_0: ──■───────
     ┌─┴─┐
q_1: ┤ X ├──■──  -> standard_gates_commutations['cx', 'cx'][None, 0] = False
     └───┘┌─┴─┐
q_2: ─────┤ X ├
          └───┘
Note that the commutation of a pair of gates is only stored in one specific order, i.e. the commutation
of a pair of cy and cx gates is only stored in standard_gates_commutations[StandardGate.CXGate, StandardGate.CYGate]. The order of the
gates is derived from the number of qubits in each gate and the value of the integer representation of
the gate name.

The values of standard_gates_commutations can be a Boolean value denoting whether the pair of gates
commute or another dictionary if the relative placement of the pair of gates has an impact on the
commutation. The relative placement is defined by the gate qubit arrangements as q2^{-1}[q1[i]] where
q1[i] is the ith qubit of the first gate and q2^{-1}[q] returns the qubit index of qubit q in the second
gate (possibly 'None'). In the second example, the zeroth qubit of cy overlaps with qubit 1 of cx. Non-
overlapping qubits are specified as 'None' in the dictionary key, e.g. example 3, there is no overlap
on the zeroth qubit of the first cx but the zeroth qubit of the second gate overlaps with qubit 1 of the
first cx.
"""

from qiskit._accelerate.circuit import StandardGate
from qiskit._accelerate.commutation_utils import CommutationLibrary


standard_gates_commutations_dict = {
    (StandardGate.IGate, StandardGate.IGate): True,
    (StandardGate.IGate, StandardGate.SXGate): True,
    (StandardGate.IGate, StandardGate.CXGate): True,
    (StandardGate.IGate, StandardGate.C3SXGate): True,
    (StandardGate.IGate, StandardGate.CCXGate): True,
    (StandardGate.IGate, StandardGate.DCXGate): True,
    (StandardGate.IGate, StandardGate.CHGate): True,
    (StandardGate.IGate, StandardGate.CSwapGate): True,
    (StandardGate.IGate, StandardGate.CSXGate): True,
    (StandardGate.IGate, StandardGate.CYGate): True,
    (StandardGate.IGate, StandardGate.CZGate): True,
    (StandardGate.IGate, StandardGate.CCZGate): True,
    (StandardGate.IGate, StandardGate.RCCXGate): True,
    (StandardGate.IGate, StandardGate.RC3XGate): True,
    (StandardGate.IGate, StandardGate.ECRGate): True,
    (StandardGate.IGate, StandardGate.SdgGate): True,
    (StandardGate.IGate, StandardGate.CSGate): True,
    (StandardGate.IGate, StandardGate.CSdgGate): True,
    (StandardGate.IGate, StandardGate.SwapGate): True,
    (StandardGate.IGate, StandardGate.ISwapGate): True,
    (StandardGate.IGate, StandardGate.SXdgGate): True,
    (StandardGate.IGate, StandardGate.TdgGate): True,
    (StandardGate.SXGate, StandardGate.SXGate): True,
    (StandardGate.SXGate, StandardGate.CXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXGate, StandardGate.C3SXGate): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    (StandardGate.SXGate, StandardGate.CCXGate): {
        (0,): False,
        (1,): False,
        (2,): True,
    },
    (StandardGate.SXGate, StandardGate.DCXGate): False,
    (StandardGate.SXGate, StandardGate.CHGate): False,
    (StandardGate.SXGate, StandardGate.CSwapGate): False,
    (StandardGate.SXGate, StandardGate.CSXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXGate, StandardGate.CYGate): False,
    (StandardGate.SXGate, StandardGate.CZGate): False,
    (StandardGate.SXGate, StandardGate.CCZGate): False,
    (StandardGate.SXGate, StandardGate.RCCXGate): False,
    (StandardGate.SXGate, StandardGate.RC3XGate): False,
    (StandardGate.SXGate, StandardGate.ECRGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXGate, StandardGate.SdgGate): False,
    (StandardGate.SXGate, StandardGate.CSGate): False,
    (StandardGate.SXGate, StandardGate.CSdgGate): False,
    (StandardGate.SXGate, StandardGate.SwapGate): False,
    (StandardGate.SXGate, StandardGate.ISwapGate): False,
    (StandardGate.SXGate, StandardGate.SXdgGate): True,
    (StandardGate.SXGate, StandardGate.TdgGate): False,
    (StandardGate.XGate, StandardGate.IGate): True,
    (StandardGate.XGate, StandardGate.SXGate): True,
    (StandardGate.XGate, StandardGate.XGate): True,
    (StandardGate.XGate, StandardGate.CXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.XGate, StandardGate.C3SXGate): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    (StandardGate.XGate, StandardGate.CCXGate): {
        (0,): False,
        (1,): False,
        (2,): True,
    },
    (StandardGate.XGate, StandardGate.DCXGate): False,
    (StandardGate.XGate, StandardGate.CHGate): False,
    (StandardGate.XGate, StandardGate.CSwapGate): False,
    (StandardGate.XGate, StandardGate.CSXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.XGate, StandardGate.CYGate): False,
    (StandardGate.XGate, StandardGate.CZGate): False,
    (StandardGate.XGate, StandardGate.CCZGate): False,
    (StandardGate.XGate, StandardGate.RCCXGate): False,
    (StandardGate.XGate, StandardGate.RC3XGate): False,
    (StandardGate.XGate, StandardGate.ECRGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.XGate, StandardGate.SdgGate): False,
    (StandardGate.XGate, StandardGate.CSGate): False,
    (StandardGate.XGate, StandardGate.CSdgGate): False,
    (StandardGate.XGate, StandardGate.SwapGate): False,
    (StandardGate.XGate, StandardGate.ISwapGate): False,
    (StandardGate.XGate, StandardGate.SXdgGate): True,
    (StandardGate.XGate, StandardGate.TdgGate): False,
    (StandardGate.XGate, StandardGate.YGate): False,
    (StandardGate.XGate, StandardGate.ZGate): False,
    (StandardGate.CXGate, StandardGate.CXGate): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CXGate, StandardGate.C3SXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    (StandardGate.CXGate, StandardGate.CCXGate): {
        (0, 1): False,
        (0, 2): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): True,
    },
    (StandardGate.CXGate, StandardGate.DCXGate): False,
    (StandardGate.CXGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CXGate, StandardGate.CSXGate): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CXGate, StandardGate.CYGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CXGate, StandardGate.CZGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CXGate, StandardGate.CCZGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): True,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CXGate, StandardGate.RCCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CXGate, StandardGate.RC3XGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CXGate, StandardGate.ECRGate): {
        (0, 1): False,
        (0, None): False,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CXGate, StandardGate.CSdgGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CXGate, StandardGate.SwapGate): False,
    (StandardGate.CXGate, StandardGate.ISwapGate): False,
    (StandardGate.C3SXGate, StandardGate.C3SXGate): {
        (0, 1, 2, 3): True,
        (0, 1, 2, None): True,
        (0, 1, 3, 2): False,
        (0, 1, 3, None): False,
        (0, 1, None, 2): False,
        (0, 1, None, 3): True,
        (0, 1, None, None): True,
        (0, 2, 1, 3): True,
        (0, 2, 1, None): True,
        (0, 2, 3, 1): False,
        (0, 2, 3, None): False,
        (0, 2, None, 1): False,
        (0, 2, None, 3): True,
        (0, 2, None, None): True,
        (0, 3, 1, 2): False,
        (0, 3, 1, None): False,
        (0, 3, 2, 1): False,
        (0, 3, 2, None): False,
        (0, 3, None, 1): False,
        (0, 3, None, 2): False,
        (0, 3, None, None): False,
        (0, None, 1, 2): False,
        (0, None, 1, 3): True,
        (0, None, 1, None): True,
        (0, None, 2, 1): False,
        (0, None, 2, 3): True,
        (0, None, 2, None): True,
        (0, None, 3, 1): False,
        (0, None, 3, 2): False,
        (0, None, 3, None): False,
        (0, None, None, 1): False,
        (0, None, None, 2): False,
        (0, None, None, 3): True,
        (0, None, None, None): True,
        (1, 0, 2, 3): True,
        (1, 0, 2, None): True,
        (1, 0, 3, 2): False,
        (1, 0, 3, None): False,
        (1, 0, None, 2): False,
        (1, 0, None, 3): True,
        (1, 0, None, None): True,
        (1, 2, 0, 3): True,
        (1, 2, 0, None): True,
        (1, 2, 3, 0): False,
        (1, 2, 3, None): False,
        (1, 2, None, 0): False,
        (1, 2, None, 3): True,
        (1, 2, None, None): True,
        (1, 3, 0, 2): False,
        (1, 3, 0, None): False,
        (1, 3, 2, 0): False,
        (1, 3, 2, None): False,
        (1, 3, None, 0): False,
        (1, 3, None, 2): False,
        (1, 3, None, None): False,
        (1, None, 0, 2): False,
        (1, None, 0, 3): True,
        (1, None, 0, None): True,
        (1, None, 2, 0): False,
        (1, None, 2, 3): True,
        (1, None, 2, None): True,
        (1, None, 3, 0): False,
        (1, None, 3, 2): False,
        (1, None, 3, None): False,
        (1, None, None, 0): False,
        (1, None, None, 2): False,
        (1, None, None, 3): True,
        (1, None, None, None): True,
        (2, 0, 1, 3): True,
        (2, 0, 1, None): True,
        (2, 0, 3, 1): False,
        (2, 0, 3, None): False,
        (2, 0, None, 1): False,
        (2, 0, None, 3): True,
        (2, 0, None, None): True,
        (2, 1, 0, 3): True,
        (2, 1, 0, None): True,
        (2, 1, 3, 0): False,
        (2, 1, 3, None): False,
        (2, 1, None, 0): False,
        (2, 1, None, 3): True,
        (2, 1, None, None): True,
        (2, 3, 0, 1): False,
        (2, 3, 0, None): False,
        (2, 3, 1, 0): False,
        (2, 3, 1, None): False,
        (2, 3, None, 0): False,
        (2, 3, None, 1): False,
        (2, 3, None, None): False,
        (2, None, 0, 1): False,
        (2, None, 0, 3): True,
        (2, None, 0, None): True,
        (2, None, 1, 0): False,
        (2, None, 1, 3): True,
        (2, None, 1, None): True,
        (2, None, 3, 0): False,
        (2, None, 3, 1): False,
        (2, None, 3, None): False,
        (2, None, None, 0): False,
        (2, None, None, 1): False,
        (2, None, None, 3): True,
        (2, None, None, None): True,
        (3, 0, 1, 2): False,
        (3, 0, 1, None): False,
        (3, 0, 2, 1): False,
        (3, 0, 2, None): False,
        (3, 0, None, 1): False,
        (3, 0, None, 2): False,
        (3, 0, None, None): False,
        (3, 1, 0, 2): False,
        (3, 1, 0, None): False,
        (3, 1, 2, 0): False,
        (3, 1, 2, None): False,
        (3, 1, None, 0): False,
        (3, 1, None, 2): False,
        (3, 1, None, None): False,
        (3, 2, 0, 1): False,
        (3, 2, 0, None): False,
        (3, 2, 1, 0): False,
        (3, 2, 1, None): False,
        (3, 2, None, 0): False,
        (3, 2, None, 1): False,
        (3, 2, None, None): False,
        (3, None, 0, 1): False,
        (3, None, 0, 2): False,
        (3, None, 0, None): False,
        (3, None, 1, 0): False,
        (3, None, 1, 2): False,
        (3, None, 1, None): False,
        (3, None, 2, 0): False,
        (3, None, 2, 1): False,
        (3, None, 2, None): False,
        (3, None, None, 0): False,
        (3, None, None, 1): False,
        (3, None, None, 2): False,
        (3, None, None, None): False,
        (None, 0, 1, 2): False,
        (None, 0, 1, 3): True,
        (None, 0, 1, None): True,
        (None, 0, 2, 1): False,
        (None, 0, 2, 3): True,
        (None, 0, 2, None): True,
        (None, 0, 3, 1): False,
        (None, 0, 3, 2): False,
        (None, 0, 3, None): False,
        (None, 0, None, 1): False,
        (None, 0, None, 2): False,
        (None, 0, None, 3): True,
        (None, 0, None, None): True,
        (None, 1, 0, 2): False,
        (None, 1, 0, 3): True,
        (None, 1, 0, None): True,
        (None, 1, 2, 0): False,
        (None, 1, 2, 3): True,
        (None, 1, 2, None): True,
        (None, 1, 3, 0): False,
        (None, 1, 3, 2): False,
        (None, 1, 3, None): False,
        (None, 1, None, 0): False,
        (None, 1, None, 2): False,
        (None, 1, None, 3): True,
        (None, 1, None, None): True,
        (None, 2, 0, 1): False,
        (None, 2, 0, 3): True,
        (None, 2, 0, None): True,
        (None, 2, 1, 0): False,
        (None, 2, 1, 3): True,
        (None, 2, 1, None): True,
        (None, 2, 3, 0): False,
        (None, 2, 3, 1): False,
        (None, 2, 3, None): False,
        (None, 2, None, 0): False,
        (None, 2, None, 1): False,
        (None, 2, None, 3): True,
        (None, 2, None, None): True,
        (None, 3, 0, 1): False,
        (None, 3, 0, 2): False,
        (None, 3, 0, None): False,
        (None, 3, 1, 0): False,
        (None, 3, 1, 2): False,
        (None, 3, 1, None): False,
        (None, 3, 2, 0): False,
        (None, 3, 2, 1): False,
        (None, 3, 2, None): False,
        (None, 3, None, 0): False,
        (None, 3, None, 1): False,
        (None, 3, None, 2): False,
        (None, 3, None, None): False,
        (None, None, 0, 1): False,
        (None, None, 0, 2): False,
        (None, None, 0, 3): True,
        (None, None, 0, None): True,
        (None, None, 1, 0): False,
        (None, None, 1, 2): False,
        (None, None, 1, 3): True,
        (None, None, 1, None): True,
        (None, None, 2, 0): False,
        (None, None, 2, 1): False,
        (None, None, 2, 3): True,
        (None, None, 2, None): True,
        (None, None, 3, 0): False,
        (None, None, 3, 1): False,
        (None, None, 3, 2): False,
        (None, None, 3, None): False,
        (None, None, None, 0): False,
        (None, None, None, 1): False,
        (None, None, None, 2): False,
        (None, None, None, 3): True,
    },
    (StandardGate.C3SXGate, StandardGate.RC3XGate): {
        (0, 1, 2, 3): False,
        (0, 1, 2, None): True,
        (0, 1, 3, 2): False,
        (0, 1, 3, None): False,
        (0, 1, None, 2): False,
        (0, 1, None, 3): False,
        (0, 1, None, None): True,
        (0, 2, 1, 3): False,
        (0, 2, 1, None): True,
        (0, 2, 3, 1): False,
        (0, 2, 3, None): False,
        (0, 2, None, 1): False,
        (0, 2, None, 3): False,
        (0, 2, None, None): True,
        (0, 3, 1, 2): False,
        (0, 3, 1, None): False,
        (0, 3, 2, 1): False,
        (0, 3, 2, None): False,
        (0, 3, None, 1): False,
        (0, 3, None, 2): False,
        (0, 3, None, None): False,
        (0, None, 1, 2): False,
        (0, None, 1, 3): False,
        (0, None, 1, None): True,
        (0, None, 2, 1): False,
        (0, None, 2, 3): False,
        (0, None, 2, None): True,
        (0, None, 3, 1): False,
        (0, None, 3, 2): False,
        (0, None, 3, None): False,
        (0, None, None, 1): False,
        (0, None, None, 2): False,
        (0, None, None, 3): False,
        (0, None, None, None): True,
        (1, 0, 2, 3): False,
        (1, 0, 2, None): True,
        (1, 0, 3, 2): False,
        (1, 0, 3, None): False,
        (1, 0, None, 2): False,
        (1, 0, None, 3): False,
        (1, 0, None, None): True,
        (1, 2, 0, 3): False,
        (1, 2, 0, None): True,
        (1, 2, 3, 0): False,
        (1, 2, 3, None): False,
        (1, 2, None, 0): False,
        (1, 2, None, 3): False,
        (1, 2, None, None): True,
        (1, 3, 0, 2): False,
        (1, 3, 0, None): False,
        (1, 3, 2, 0): False,
        (1, 3, 2, None): False,
        (1, 3, None, 0): False,
        (1, 3, None, 2): False,
        (1, 3, None, None): False,
        (1, None, 0, 2): False,
        (1, None, 0, 3): False,
        (1, None, 0, None): True,
        (1, None, 2, 0): False,
        (1, None, 2, 3): False,
        (1, None, 2, None): True,
        (1, None, 3, 0): False,
        (1, None, 3, 2): False,
        (1, None, 3, None): False,
        (1, None, None, 0): False,
        (1, None, None, 2): False,
        (1, None, None, 3): False,
        (1, None, None, None): True,
        (2, 0, 1, 3): False,
        (2, 0, 1, None): True,
        (2, 0, 3, 1): False,
        (2, 0, 3, None): False,
        (2, 0, None, 1): False,
        (2, 0, None, 3): False,
        (2, 0, None, None): True,
        (2, 1, 0, 3): False,
        (2, 1, 0, None): True,
        (2, 1, 3, 0): False,
        (2, 1, 3, None): False,
        (2, 1, None, 0): False,
        (2, 1, None, 3): False,
        (2, 1, None, None): True,
        (2, 3, 0, 1): False,
        (2, 3, 0, None): False,
        (2, 3, 1, 0): False,
        (2, 3, 1, None): False,
        (2, 3, None, 0): False,
        (2, 3, None, 1): False,
        (2, 3, None, None): False,
        (2, None, 0, 1): False,
        (2, None, 0, 3): False,
        (2, None, 0, None): True,
        (2, None, 1, 0): False,
        (2, None, 1, 3): False,
        (2, None, 1, None): True,
        (2, None, 3, 0): False,
        (2, None, 3, 1): False,
        (2, None, 3, None): False,
        (2, None, None, 0): False,
        (2, None, None, 1): False,
        (2, None, None, 3): False,
        (2, None, None, None): True,
        (3, 0, 1, 2): False,
        (3, 0, 1, None): False,
        (3, 0, 2, 1): False,
        (3, 0, 2, None): False,
        (3, 0, None, 1): False,
        (3, 0, None, 2): False,
        (3, 0, None, None): False,
        (3, 1, 0, 2): False,
        (3, 1, 0, None): False,
        (3, 1, 2, 0): False,
        (3, 1, 2, None): False,
        (3, 1, None, 0): False,
        (3, 1, None, 2): False,
        (3, 1, None, None): False,
        (3, 2, 0, 1): False,
        (3, 2, 0, None): False,
        (3, 2, 1, 0): False,
        (3, 2, 1, None): False,
        (3, 2, None, 0): False,
        (3, 2, None, 1): False,
        (3, 2, None, None): False,
        (3, None, 0, 1): False,
        (3, None, 0, 2): False,
        (3, None, 0, None): False,
        (3, None, 1, 0): False,
        (3, None, 1, 2): False,
        (3, None, 1, None): False,
        (3, None, 2, 0): False,
        (3, None, 2, 1): False,
        (3, None, 2, None): False,
        (3, None, None, 0): False,
        (3, None, None, 1): False,
        (3, None, None, 2): False,
        (3, None, None, None): False,
        (None, 0, 1, 2): False,
        (None, 0, 1, 3): False,
        (None, 0, 1, None): True,
        (None, 0, 2, 1): False,
        (None, 0, 2, 3): False,
        (None, 0, 2, None): True,
        (None, 0, 3, 1): False,
        (None, 0, 3, 2): False,
        (None, 0, 3, None): False,
        (None, 0, None, 1): False,
        (None, 0, None, 2): False,
        (None, 0, None, 3): False,
        (None, 0, None, None): True,
        (None, 1, 0, 2): False,
        (None, 1, 0, 3): False,
        (None, 1, 0, None): True,
        (None, 1, 2, 0): False,
        (None, 1, 2, 3): False,
        (None, 1, 2, None): True,
        (None, 1, 3, 0): False,
        (None, 1, 3, 2): False,
        (None, 1, 3, None): False,
        (None, 1, None, 0): False,
        (None, 1, None, 2): False,
        (None, 1, None, 3): False,
        (None, 1, None, None): True,
        (None, 2, 0, 1): False,
        (None, 2, 0, 3): False,
        (None, 2, 0, None): True,
        (None, 2, 1, 0): False,
        (None, 2, 1, 3): False,
        (None, 2, 1, None): True,
        (None, 2, 3, 0): False,
        (None, 2, 3, 1): False,
        (None, 2, 3, None): False,
        (None, 2, None, 0): False,
        (None, 2, None, 1): False,
        (None, 2, None, 3): False,
        (None, 2, None, None): True,
        (None, 3, 0, 1): False,
        (None, 3, 0, 2): False,
        (None, 3, 0, None): False,
        (None, 3, 1, 0): False,
        (None, 3, 1, 2): False,
        (None, 3, 1, None): False,
        (None, 3, 2, 0): False,
        (None, 3, 2, 1): False,
        (None, 3, 2, None): False,
        (None, 3, None, 0): False,
        (None, 3, None, 1): False,
        (None, 3, None, 2): False,
        (None, 3, None, None): False,
        (None, None, 0, 1): False,
        (None, None, 0, 2): False,
        (None, None, 0, 3): False,
        (None, None, 0, None): True,
        (None, None, 1, 0): False,
        (None, None, 1, 2): False,
        (None, None, 1, 3): False,
        (None, None, 1, None): True,
        (None, None, 2, 0): False,
        (None, None, 2, 1): False,
        (None, None, 2, 3): False,
        (None, None, 2, None): True,
        (None, None, 3, 0): False,
        (None, None, 3, 1): False,
        (None, None, 3, 2): False,
        (None, None, 3, None): False,
        (None, None, None, 0): False,
        (None, None, None, 1): False,
        (None, None, None, 2): False,
        (None, None, None, 3): False,
    },
    (StandardGate.CCXGate, StandardGate.C3SXGate): {
        (0, 1, 2): False,
        (0, 1, 3): True,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): True,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): True,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): True,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): True,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): True,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): True,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): True,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): True,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): True,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): True,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): True,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): True,
    },
    (StandardGate.CCXGate, StandardGate.CCXGate): {
        (0, 1, 2): True,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): True,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): True,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): True,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): True,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): True,
    },
    (StandardGate.CCXGate, StandardGate.CSwapGate): {
        (0, 1, 2): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): False,
        (1, 2, 0): True,
        (1, 2, None): True,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): False,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, None): True,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.CCXGate, StandardGate.CCZGate): {
        (0, 1, 2): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): True,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): True,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, None): True,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): True,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): True,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.CCXGate, StandardGate.RCCXGate): {
        (0, 1, 2): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.CCXGate, StandardGate.RC3XGate): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    (StandardGate.DCXGate, StandardGate.C3SXGate): False,
    (StandardGate.DCXGate, StandardGate.CCXGate): False,
    (StandardGate.DCXGate, StandardGate.DCXGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.DCXGate, StandardGate.CSwapGate): False,
    (StandardGate.DCXGate, StandardGate.CCZGate): False,
    (StandardGate.DCXGate, StandardGate.RCCXGate): False,
    (StandardGate.DCXGate, StandardGate.RC3XGate): False,
    (StandardGate.DCXGate, StandardGate.ECRGate): False,
    (StandardGate.DCXGate, StandardGate.CSdgGate): False,
    (StandardGate.DCXGate, StandardGate.SwapGate): False,
    (StandardGate.DCXGate, StandardGate.ISwapGate): False,
    (StandardGate.CHGate, StandardGate.CXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.C3SXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CHGate, StandardGate.CCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CHGate, StandardGate.DCXGate): False,
    (StandardGate.CHGate, StandardGate.CHGate): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CHGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CHGate, StandardGate.CSXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.CYGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.CZGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.CCZGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): True,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CHGate, StandardGate.RCCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CHGate, StandardGate.RC3XGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CHGate, StandardGate.ECRGate): False,
    (StandardGate.CHGate, StandardGate.CSGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.CSdgGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CHGate, StandardGate.SwapGate): False,
    (StandardGate.CHGate, StandardGate.ISwapGate): False,
    (StandardGate.CSwapGate, StandardGate.C3SXGate): {
        (0, 1, 2): True,
        (0, 1, 3): False,
        (0, 1, None): False,
        (0, 2, 1): True,
        (0, 2, 3): False,
        (0, 2, None): False,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, 3): False,
        (1, 0, None): False,
        (1, 2, 0): True,
        (1, 2, 3): False,
        (1, 2, None): False,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): False,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): True,
        (3, 0, 2): True,
        (3, 0, None): False,
        (3, 1, 0): True,
        (3, 1, 2): True,
        (3, 1, None): False,
        (3, 2, 0): True,
        (3, 2, 1): True,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): True,
        (None, 0, 3): False,
        (None, 0, None): False,
        (None, 1, 0): True,
        (None, 1, 2): True,
        (None, 1, 3): False,
        (None, 1, None): False,
        (None, 2, 0): True,
        (None, 2, 1): True,
        (None, 2, 3): False,
        (None, 2, None): False,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    (StandardGate.CSwapGate, StandardGate.CSwapGate): {
        (0, 1, 2): True,
        (0, 1, None): False,
        (0, 2, 1): True,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): False,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): False,
        (None, 1, 0): False,
        (None, 1, 2): True,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): True,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.CSwapGate, StandardGate.RC3XGate): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): False,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): False,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): False,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): True,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): True,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): False,
        (None, 1, 0): True,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): False,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    (StandardGate.CSXGate, StandardGate.C3SXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    (StandardGate.CSXGate, StandardGate.CCXGate): {
        (0, 1): False,
        (0, 2): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): True,
    },
    (StandardGate.CSXGate, StandardGate.DCXGate): False,
    (StandardGate.CSXGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CSXGate, StandardGate.CSXGate): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CSXGate, StandardGate.CCZGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): True,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CSXGate, StandardGate.RCCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CSXGate, StandardGate.RC3XGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CSXGate, StandardGate.ECRGate): {
        (0, 1): False,
        (0, None): False,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CSXGate, StandardGate.CSdgGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CSXGate, StandardGate.SwapGate): False,
    (StandardGate.CSXGate, StandardGate.ISwapGate): False,
    (StandardGate.CYGate, StandardGate.C3SXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CYGate, StandardGate.CCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CYGate, StandardGate.DCXGate): False,
    (StandardGate.CYGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CYGate, StandardGate.CSXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CYGate, StandardGate.CYGate): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.CYGate, StandardGate.CZGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CYGate, StandardGate.CCZGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): True,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CYGate, StandardGate.RCCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CYGate, StandardGate.RC3XGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.CYGate, StandardGate.ECRGate): False,
    (StandardGate.CYGate, StandardGate.CSdgGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CYGate, StandardGate.SwapGate): False,
    (StandardGate.CYGate, StandardGate.ISwapGate): False,
    (StandardGate.CZGate, StandardGate.C3SXGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CZGate, StandardGate.CCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CZGate, StandardGate.DCXGate): False,
    (StandardGate.CZGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): True,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CZGate, StandardGate.CSXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
    (StandardGate.CZGate, StandardGate.CZGate): True,
    (StandardGate.CZGate, StandardGate.CCZGate): True,
    (StandardGate.CZGate, StandardGate.RCCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CZGate, StandardGate.RC3XGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CZGate, StandardGate.ECRGate): False,
    (StandardGate.CZGate, StandardGate.CSdgGate): True,
    (StandardGate.CZGate, StandardGate.SwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CZGate, StandardGate.ISwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CCZGate, StandardGate.C3SXGate): {
        (0, 1, 2): True,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): True,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): True,
        (0, None, 2): True,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): True,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): True,
        (1, None, 2): True,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): True,
        (2, None, 1): True,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): True,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): True,
        (None, 1, 2): True,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): True,
        (None, 2, 1): True,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): True,
        (None, None, 1): True,
        (None, None, 2): True,
        (None, None, 3): False,
    },
    (StandardGate.CCZGate, StandardGate.CSwapGate): {
        (0, 1, 2): True,
        (0, 1, None): False,
        (0, 2, 1): True,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, None): False,
        (1, 2, 0): True,
        (1, 2, None): True,
        (1, None, 0): False,
        (1, None, 2): True,
        (1, None, None): False,
        (2, 0, 1): True,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, None): True,
        (2, None, 0): False,
        (2, None, 1): True,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): True,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): True,
        (None, 2, None): False,
        (None, None, 0): True,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.CCZGate, StandardGate.CCZGate): True,
    (StandardGate.CCZGate, StandardGate.RCCXGate): {
        (0, 1, 2): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): True,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): True,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): True,
        (None, 1, 2): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): True,
        (None, None, 1): True,
        (None, None, 2): False,
    },
    (StandardGate.CCZGate, StandardGate.RC3XGate): {
        (0, 1, 2): True,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): True,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): True,
        (0, None, 2): True,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): True,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): True,
        (1, None, 2): True,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): True,
        (2, None, 1): True,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): True,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): True,
        (None, 1, 2): True,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): True,
        (None, 2, 1): True,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): True,
        (None, None, 1): True,
        (None, None, 2): True,
        (None, None, 3): False,
    },
    (StandardGate.HGate, StandardGate.IGate): True,
    (StandardGate.HGate, StandardGate.SXGate): False,
    (StandardGate.HGate, StandardGate.XGate): False,
    (StandardGate.HGate, StandardGate.CXGate): False,
    (StandardGate.HGate, StandardGate.C3SXGate): False,
    (StandardGate.HGate, StandardGate.CCXGate): False,
    (StandardGate.HGate, StandardGate.DCXGate): False,
    (StandardGate.HGate, StandardGate.CHGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.HGate, StandardGate.CSwapGate): False,
    (StandardGate.HGate, StandardGate.CSXGate): False,
    (StandardGate.HGate, StandardGate.CYGate): False,
    (StandardGate.HGate, StandardGate.CZGate): False,
    (StandardGate.HGate, StandardGate.CCZGate): False,
    (StandardGate.HGate, StandardGate.HGate): True,
    (StandardGate.HGate, StandardGate.RCCXGate): False,
    (StandardGate.HGate, StandardGate.RC3XGate): False,
    (StandardGate.HGate, StandardGate.ECRGate): False,
    (StandardGate.HGate, StandardGate.SGate): False,
    (StandardGate.HGate, StandardGate.SdgGate): False,
    (StandardGate.HGate, StandardGate.CSGate): False,
    (StandardGate.HGate, StandardGate.CSdgGate): False,
    (StandardGate.HGate, StandardGate.SwapGate): False,
    (StandardGate.HGate, StandardGate.ISwapGate): False,
    (StandardGate.HGate, StandardGate.SXdgGate): False,
    (StandardGate.HGate, StandardGate.TGate): False,
    (StandardGate.HGate, StandardGate.TdgGate): False,
    (StandardGate.HGate, StandardGate.YGate): False,
    (StandardGate.HGate, StandardGate.ZGate): False,
    (StandardGate.RCCXGate, StandardGate.C3SXGate): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    (StandardGate.RCCXGate, StandardGate.CSwapGate): {
        (0, 1, 2): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): False,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.RCCXGate, StandardGate.RCCXGate): {
        (0, 1, 2): True,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): True,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    (StandardGate.RCCXGate, StandardGate.RC3XGate): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): True,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): True,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): True,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): True,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): True,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    (StandardGate.RC3XGate, StandardGate.RC3XGate): {
        (0, 1, 2, 3): True,
        (0, 1, 2, None): True,
        (0, 1, 3, 2): False,
        (0, 1, 3, None): False,
        (0, 1, None, 2): False,
        (0, 1, None, 3): False,
        (0, 1, None, None): True,
        (0, 2, 1, 3): True,
        (0, 2, 1, None): True,
        (0, 2, 3, 1): False,
        (0, 2, 3, None): False,
        (0, 2, None, 1): False,
        (0, 2, None, 3): False,
        (0, 2, None, None): True,
        (0, 3, 1, 2): False,
        (0, 3, 1, None): False,
        (0, 3, 2, 1): False,
        (0, 3, 2, None): False,
        (0, 3, None, 1): False,
        (0, 3, None, 2): False,
        (0, 3, None, None): False,
        (0, None, 1, 2): False,
        (0, None, 1, 3): False,
        (0, None, 1, None): True,
        (0, None, 2, 1): False,
        (0, None, 2, 3): True,
        (0, None, 2, None): True,
        (0, None, 3, 1): False,
        (0, None, 3, 2): False,
        (0, None, 3, None): False,
        (0, None, None, 1): False,
        (0, None, None, 2): False,
        (0, None, None, 3): False,
        (0, None, None, None): True,
        (1, 0, 2, 3): True,
        (1, 0, 2, None): True,
        (1, 0, 3, 2): False,
        (1, 0, 3, None): False,
        (1, 0, None, 2): False,
        (1, 0, None, 3): False,
        (1, 0, None, None): True,
        (1, 2, 0, 3): True,
        (1, 2, 0, None): True,
        (1, 2, 3, 0): False,
        (1, 2, 3, None): False,
        (1, 2, None, 0): False,
        (1, 2, None, 3): False,
        (1, 2, None, None): True,
        (1, 3, 0, 2): False,
        (1, 3, 0, None): False,
        (1, 3, 2, 0): False,
        (1, 3, 2, None): False,
        (1, 3, None, 0): False,
        (1, 3, None, 2): False,
        (1, 3, None, None): False,
        (1, None, 0, 2): False,
        (1, None, 0, 3): False,
        (1, None, 0, None): True,
        (1, None, 2, 0): False,
        (1, None, 2, 3): True,
        (1, None, 2, None): True,
        (1, None, 3, 0): False,
        (1, None, 3, 2): False,
        (1, None, 3, None): False,
        (1, None, None, 0): False,
        (1, None, None, 2): False,
        (1, None, None, 3): False,
        (1, None, None, None): True,
        (2, 0, 1, 3): True,
        (2, 0, 1, None): True,
        (2, 0, 3, 1): False,
        (2, 0, 3, None): False,
        (2, 0, None, 1): False,
        (2, 0, None, 3): False,
        (2, 0, None, None): True,
        (2, 1, 0, 3): True,
        (2, 1, 0, None): True,
        (2, 1, 3, 0): False,
        (2, 1, 3, None): False,
        (2, 1, None, 0): False,
        (2, 1, None, 3): False,
        (2, 1, None, None): True,
        (2, 3, 0, 1): False,
        (2, 3, 0, None): False,
        (2, 3, 1, 0): False,
        (2, 3, 1, None): False,
        (2, 3, None, 0): False,
        (2, 3, None, 1): False,
        (2, 3, None, None): False,
        (2, None, 0, 1): False,
        (2, None, 0, 3): True,
        (2, None, 0, None): True,
        (2, None, 1, 0): False,
        (2, None, 1, 3): True,
        (2, None, 1, None): True,
        (2, None, 3, 0): False,
        (2, None, 3, 1): False,
        (2, None, 3, None): False,
        (2, None, None, 0): False,
        (2, None, None, 1): False,
        (2, None, None, 3): False,
        (2, None, None, None): True,
        (3, 0, 1, 2): False,
        (3, 0, 1, None): False,
        (3, 0, 2, 1): False,
        (3, 0, 2, None): False,
        (3, 0, None, 1): False,
        (3, 0, None, 2): False,
        (3, 0, None, None): False,
        (3, 1, 0, 2): False,
        (3, 1, 0, None): False,
        (3, 1, 2, 0): False,
        (3, 1, 2, None): False,
        (3, 1, None, 0): False,
        (3, 1, None, 2): False,
        (3, 1, None, None): False,
        (3, 2, 0, 1): False,
        (3, 2, 0, None): False,
        (3, 2, 1, 0): False,
        (3, 2, 1, None): False,
        (3, 2, None, 0): False,
        (3, 2, None, 1): False,
        (3, 2, None, None): False,
        (3, None, 0, 1): False,
        (3, None, 0, 2): False,
        (3, None, 0, None): False,
        (3, None, 1, 0): False,
        (3, None, 1, 2): False,
        (3, None, 1, None): False,
        (3, None, 2, 0): False,
        (3, None, 2, 1): False,
        (3, None, 2, None): False,
        (3, None, None, 0): False,
        (3, None, None, 1): False,
        (3, None, None, 2): False,
        (3, None, None, None): False,
        (None, 0, 1, 2): False,
        (None, 0, 1, 3): False,
        (None, 0, 1, None): True,
        (None, 0, 2, 1): False,
        (None, 0, 2, 3): True,
        (None, 0, 2, None): True,
        (None, 0, 3, 1): False,
        (None, 0, 3, 2): False,
        (None, 0, 3, None): False,
        (None, 0, None, 1): False,
        (None, 0, None, 2): False,
        (None, 0, None, 3): False,
        (None, 0, None, None): True,
        (None, 1, 0, 2): False,
        (None, 1, 0, 3): False,
        (None, 1, 0, None): True,
        (None, 1, 2, 0): False,
        (None, 1, 2, 3): True,
        (None, 1, 2, None): True,
        (None, 1, 3, 0): False,
        (None, 1, 3, 2): False,
        (None, 1, 3, None): False,
        (None, 1, None, 0): False,
        (None, 1, None, 2): False,
        (None, 1, None, 3): False,
        (None, 1, None, None): True,
        (None, 2, 0, 1): False,
        (None, 2, 0, 3): True,
        (None, 2, 0, None): True,
        (None, 2, 1, 0): False,
        (None, 2, 1, 3): True,
        (None, 2, 1, None): True,
        (None, 2, 3, 0): False,
        (None, 2, 3, 1): False,
        (None, 2, 3, None): False,
        (None, 2, None, 0): False,
        (None, 2, None, 1): False,
        (None, 2, None, 3): False,
        (None, 2, None, None): True,
        (None, 3, 0, 1): False,
        (None, 3, 0, 2): False,
        (None, 3, 0, None): False,
        (None, 3, 1, 0): False,
        (None, 3, 1, 2): False,
        (None, 3, 1, None): False,
        (None, 3, 2, 0): False,
        (None, 3, 2, 1): False,
        (None, 3, 2, None): False,
        (None, 3, None, 0): False,
        (None, 3, None, 1): False,
        (None, 3, None, 2): False,
        (None, 3, None, None): False,
        (None, None, 0, 1): False,
        (None, None, 0, 2): False,
        (None, None, 0, 3): False,
        (None, None, 0, None): True,
        (None, None, 1, 0): False,
        (None, None, 1, 2): False,
        (None, None, 1, 3): False,
        (None, None, 1, None): True,
        (None, None, 2, 0): False,
        (None, None, 2, 1): False,
        (None, None, 2, 3): True,
        (None, None, 2, None): True,
        (None, None, 3, 0): False,
        (None, None, 3, 1): False,
        (None, None, 3, 2): False,
        (None, None, 3, None): False,
        (None, None, None, 0): False,
        (None, None, None, 1): False,
        (None, None, None, 2): False,
        (None, None, None, 3): False,
    },
    (StandardGate.ECRGate, StandardGate.C3SXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    (StandardGate.ECRGate, StandardGate.CCXGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): True,
    },
    (StandardGate.ECRGate, StandardGate.CSwapGate): False,
    (StandardGate.ECRGate, StandardGate.CCZGate): False,
    (StandardGate.ECRGate, StandardGate.RCCXGate): False,
    (StandardGate.ECRGate, StandardGate.RC3XGate): False,
    (StandardGate.ECRGate, StandardGate.ECRGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    (StandardGate.ECRGate, StandardGate.CSdgGate): False,
    (StandardGate.ECRGate, StandardGate.SwapGate): False,
    (StandardGate.ECRGate, StandardGate.ISwapGate): False,
    (StandardGate.SGate, StandardGate.IGate): True,
    (StandardGate.SGate, StandardGate.SXGate): False,
    (StandardGate.SGate, StandardGate.XGate): False,
    (StandardGate.SGate, StandardGate.CXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SGate, StandardGate.C3SXGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.SGate, StandardGate.CCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.SGate, StandardGate.DCXGate): False,
    (StandardGate.SGate, StandardGate.CHGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SGate, StandardGate.CSwapGate): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    (StandardGate.SGate, StandardGate.CSXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SGate, StandardGate.CYGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SGate, StandardGate.CZGate): True,
    (StandardGate.SGate, StandardGate.CCZGate): True,
    (StandardGate.SGate, StandardGate.RCCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.SGate, StandardGate.RC3XGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.SGate, StandardGate.ECRGate): False,
    (StandardGate.SGate, StandardGate.SGate): True,
    (StandardGate.SGate, StandardGate.SdgGate): True,
    (StandardGate.SGate, StandardGate.CSGate): True,
    (StandardGate.SGate, StandardGate.CSdgGate): True,
    (StandardGate.SGate, StandardGate.SwapGate): False,
    (StandardGate.SGate, StandardGate.ISwapGate): False,
    (StandardGate.SGate, StandardGate.SXdgGate): False,
    (StandardGate.SGate, StandardGate.TGate): True,
    (StandardGate.SGate, StandardGate.TdgGate): True,
    (StandardGate.SGate, StandardGate.YGate): False,
    (StandardGate.SGate, StandardGate.ZGate): True,
    (StandardGate.SdgGate, StandardGate.CXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SdgGate, StandardGate.C3SXGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.SdgGate, StandardGate.CCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.SdgGate, StandardGate.DCXGate): False,
    (StandardGate.SdgGate, StandardGate.CHGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SdgGate, StandardGate.CSwapGate): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    (StandardGate.SdgGate, StandardGate.CSXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SdgGate, StandardGate.CYGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.SdgGate, StandardGate.CZGate): True,
    (StandardGate.SdgGate, StandardGate.CCZGate): True,
    (StandardGate.SdgGate, StandardGate.RCCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.SdgGate, StandardGate.RC3XGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.SdgGate, StandardGate.ECRGate): False,
    (StandardGate.SdgGate, StandardGate.SdgGate): True,
    (StandardGate.SdgGate, StandardGate.CSGate): True,
    (StandardGate.SdgGate, StandardGate.CSdgGate): True,
    (StandardGate.SdgGate, StandardGate.SwapGate): False,
    (StandardGate.SdgGate, StandardGate.ISwapGate): False,
    (StandardGate.SdgGate, StandardGate.SXdgGate): False,
    (StandardGate.SdgGate, StandardGate.TdgGate): True,
    (StandardGate.CSGate, StandardGate.CXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
    (StandardGate.CSGate, StandardGate.C3SXGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CSGate, StandardGate.CCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CSGate, StandardGate.DCXGate): False,
    (StandardGate.CSGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): True,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CSGate, StandardGate.CSXGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
    (StandardGate.CSGate, StandardGate.CYGate): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
    (StandardGate.CSGate, StandardGate.CZGate): True,
    (StandardGate.CSGate, StandardGate.CCZGate): True,
    (StandardGate.CSGate, StandardGate.RCCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CSGate, StandardGate.RC3XGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CSGate, StandardGate.ECRGate): False,
    (StandardGate.CSGate, StandardGate.CSGate): True,
    (StandardGate.CSGate, StandardGate.CSdgGate): True,
    (StandardGate.CSGate, StandardGate.SwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CSGate, StandardGate.ISwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CSdgGate, StandardGate.C3SXGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CSdgGate, StandardGate.CCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CSdgGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): True,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.CSdgGate, StandardGate.CCZGate): True,
    (StandardGate.CSdgGate, StandardGate.RCCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    (StandardGate.CSdgGate, StandardGate.RC3XGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    (StandardGate.CSdgGate, StandardGate.CSdgGate): True,
    (StandardGate.CSdgGate, StandardGate.SwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.CSdgGate, StandardGate.ISwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.SwapGate, StandardGate.C3SXGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.SwapGate, StandardGate.CCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.SwapGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.SwapGate, StandardGate.CCZGate): {
        (0, 1): True,
        (0, 2): True,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.SwapGate, StandardGate.RCCXGate): False,
    (StandardGate.SwapGate, StandardGate.RC3XGate): {
        (0, 1): True,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.SwapGate, StandardGate.SwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.SwapGate, StandardGate.ISwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.ISwapGate, StandardGate.C3SXGate): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.ISwapGate, StandardGate.CCXGate): {
        (0, 1): True,
        (0, 2): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.ISwapGate, StandardGate.CSwapGate): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.ISwapGate, StandardGate.CCZGate): {
        (0, 1): True,
        (0, 2): True,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    (StandardGate.ISwapGate, StandardGate.RCCXGate): False,
    (StandardGate.ISwapGate, StandardGate.RC3XGate): {
        (0, 1): True,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    (StandardGate.ISwapGate, StandardGate.ISwapGate): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    (StandardGate.SXdgGate, StandardGate.CXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXdgGate, StandardGate.C3SXGate): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    (StandardGate.SXdgGate, StandardGate.CCXGate): {
        (0,): False,
        (1,): False,
        (2,): True,
    },
    (StandardGate.SXdgGate, StandardGate.DCXGate): False,
    (StandardGate.SXdgGate, StandardGate.CHGate): False,
    (StandardGate.SXdgGate, StandardGate.CSwapGate): False,
    (StandardGate.SXdgGate, StandardGate.CSXGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXdgGate, StandardGate.CYGate): False,
    (StandardGate.SXdgGate, StandardGate.CZGate): False,
    (StandardGate.SXdgGate, StandardGate.CCZGate): False,
    (StandardGate.SXdgGate, StandardGate.RCCXGate): False,
    (StandardGate.SXdgGate, StandardGate.RC3XGate): False,
    (StandardGate.SXdgGate, StandardGate.ECRGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.SXdgGate, StandardGate.CSGate): False,
    (StandardGate.SXdgGate, StandardGate.CSdgGate): False,
    (StandardGate.SXdgGate, StandardGate.SwapGate): False,
    (StandardGate.SXdgGate, StandardGate.ISwapGate): False,
    (StandardGate.SXdgGate, StandardGate.SXdgGate): True,
    (StandardGate.TGate, StandardGate.IGate): True,
    (StandardGate.TGate, StandardGate.SXGate): False,
    (StandardGate.TGate, StandardGate.XGate): False,
    (StandardGate.TGate, StandardGate.CXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TGate, StandardGate.C3SXGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.TGate, StandardGate.CCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.TGate, StandardGate.DCXGate): False,
    (StandardGate.TGate, StandardGate.CHGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TGate, StandardGate.CSwapGate): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    (StandardGate.TGate, StandardGate.CSXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TGate, StandardGate.CYGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TGate, StandardGate.CZGate): True,
    (StandardGate.TGate, StandardGate.CCZGate): True,
    (StandardGate.TGate, StandardGate.RCCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.TGate, StandardGate.RC3XGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.TGate, StandardGate.ECRGate): False,
    (StandardGate.TGate, StandardGate.SdgGate): True,
    (StandardGate.TGate, StandardGate.CSGate): True,
    (StandardGate.TGate, StandardGate.CSdgGate): True,
    (StandardGate.TGate, StandardGate.SwapGate): False,
    (StandardGate.TGate, StandardGate.ISwapGate): False,
    (StandardGate.TGate, StandardGate.SXdgGate): False,
    (StandardGate.TGate, StandardGate.TGate): True,
    (StandardGate.TGate, StandardGate.TdgGate): True,
    (StandardGate.TGate, StandardGate.YGate): False,
    (StandardGate.TGate, StandardGate.ZGate): True,
    (StandardGate.TdgGate, StandardGate.CXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TdgGate, StandardGate.C3SXGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.TdgGate, StandardGate.CCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.TdgGate, StandardGate.DCXGate): False,
    (StandardGate.TdgGate, StandardGate.CHGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TdgGate, StandardGate.CSwapGate): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    (StandardGate.TdgGate, StandardGate.CSXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TdgGate, StandardGate.CYGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.TdgGate, StandardGate.CZGate): True,
    (StandardGate.TdgGate, StandardGate.CCZGate): True,
    (StandardGate.TdgGate, StandardGate.RCCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.TdgGate, StandardGate.RC3XGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.TdgGate, StandardGate.ECRGate): False,
    (StandardGate.TdgGate, StandardGate.CSGate): True,
    (StandardGate.TdgGate, StandardGate.CSdgGate): True,
    (StandardGate.TdgGate, StandardGate.SwapGate): False,
    (StandardGate.TdgGate, StandardGate.ISwapGate): False,
    (StandardGate.TdgGate, StandardGate.SXdgGate): False,
    (StandardGate.TdgGate, StandardGate.TdgGate): True,
    (StandardGate.YGate, StandardGate.IGate): True,
    (StandardGate.YGate, StandardGate.SXGate): False,
    (StandardGate.YGate, StandardGate.CXGate): False,
    (StandardGate.YGate, StandardGate.C3SXGate): False,
    (StandardGate.YGate, StandardGate.CCXGate): False,
    (StandardGate.YGate, StandardGate.DCXGate): False,
    (StandardGate.YGate, StandardGate.CHGate): False,
    (StandardGate.YGate, StandardGate.CSwapGate): False,
    (StandardGate.YGate, StandardGate.CSXGate): False,
    (StandardGate.YGate, StandardGate.CYGate): {
        (0,): False,
        (1,): True,
    },
    (StandardGate.YGate, StandardGate.CZGate): False,
    (StandardGate.YGate, StandardGate.CCZGate): False,
    (StandardGate.YGate, StandardGate.RCCXGate): False,
    (StandardGate.YGate, StandardGate.RC3XGate): False,
    (StandardGate.YGate, StandardGate.ECRGate): False,
    (StandardGate.YGate, StandardGate.SdgGate): False,
    (StandardGate.YGate, StandardGate.CSGate): False,
    (StandardGate.YGate, StandardGate.CSdgGate): False,
    (StandardGate.YGate, StandardGate.SwapGate): False,
    (StandardGate.YGate, StandardGate.ISwapGate): False,
    (StandardGate.YGate, StandardGate.SXdgGate): False,
    (StandardGate.YGate, StandardGate.TdgGate): False,
    (StandardGate.YGate, StandardGate.YGate): True,
    (StandardGate.YGate, StandardGate.ZGate): False,
    (StandardGate.ZGate, StandardGate.IGate): True,
    (StandardGate.ZGate, StandardGate.SXGate): False,
    (StandardGate.ZGate, StandardGate.CXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.ZGate, StandardGate.C3SXGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.ZGate, StandardGate.CCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.ZGate, StandardGate.DCXGate): False,
    (StandardGate.ZGate, StandardGate.CHGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.ZGate, StandardGate.CSwapGate): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    (StandardGate.ZGate, StandardGate.CSXGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.ZGate, StandardGate.CYGate): {
        (0,): True,
        (1,): False,
    },
    (StandardGate.ZGate, StandardGate.CZGate): True,
    (StandardGate.ZGate, StandardGate.CCZGate): True,
    (StandardGate.ZGate, StandardGate.RCCXGate): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    (StandardGate.ZGate, StandardGate.RC3XGate): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    (StandardGate.ZGate, StandardGate.ECRGate): False,
    (StandardGate.ZGate, StandardGate.SdgGate): True,
    (StandardGate.ZGate, StandardGate.CSGate): True,
    (StandardGate.ZGate, StandardGate.CSdgGate): True,
    (StandardGate.ZGate, StandardGate.SwapGate): False,
    (StandardGate.ZGate, StandardGate.ISwapGate): False,
    (StandardGate.ZGate, StandardGate.SXdgGate): False,
    (StandardGate.ZGate, StandardGate.TdgGate): True,
    (StandardGate.ZGate, StandardGate.ZGate): True,
}

standard_gates_commutations = CommutationLibrary(standard_gates_commutations_dict)
